export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const FETCH_LOCATION_FAILED = 'FETCH_LOCATION_FAILED';
export const SET_ANY_LOCATION_DATA = 'SET_ANY_LOCATION_DATA';
export const FETCH_ANY_LOCATION_FAILED = 'FETCH_ANY_LOCATION_FAILED';

export const GET_NBA_WEEK = 'GET_NBA_WEEK';
export const SET_NBA_WEEK = 'SET_NBA_WEEK';

export const CHANGE_PHOTO = 'CHANGE_PHOTO';